name: Rename Godot file

on:
  push:
    branches:
      - main

jobs:
  rename-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rename Зєфалятор Казла.wasm
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Перейменування одного файлу
          mv "ЗєфаляторКазла/Зєфалятор Казла.wasm" "ЗєфаляторКазла/goatzefalator.wasm"
          
          git add "ЗєфаляторКазла/goatzefalator.wasm"
          git commit -m "Rename Зєфалятор Казла.wasm to goatzefalator.wasm" || echo "No changes to commit"
          
          # Пуш через PAT
          git push https://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@github.com/Ua3012/ZefaApps.git main
