name: Rename Godot files

on:
  push:
    branches:
      - main

jobs:
  rename-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rename Godot files
        run: |
          # Створимо папку для нового збереження
          mkdir -p renamed_files
          
          # Перейменування файлів
          mv "ЗєфаляторКазла/Зєфалятор Казла.wasm" "ЗєфаляторКазла/goatzefalator.wasm"

      - name: Push renamed files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add renamed_files/
          git commit -m "Rename Godot files to latin names"
          git push origin main
