# name: GoatZefalator.zip

# on:
#   push:
#     branches:
#       - main

# permissions:
#   contents: write

# jobs:
#   unzip:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Завантаження репозиторію (з LFS файлами)
#         uses: actions/checkout@v4
#         with:
#           lfs: true

#       - name: FFF
#         run: |
#           sudo apt-get update
#           sudo apt-get install git-lfs -y
#           git lfs install

#           #git lfs track "ЗєфаляторКазла/*.pck"

#           git add .gitattributes

#       - name: Розпакування ZIP
#         run: |
#           mkdir -p ЗєфаляторКазла
#           unzip -o "GoatZefalator.zip" -d ЗєфаляторКазла

#       - name: Коміт і пуш результатів
#         run: |
#           git config user.name "github-actions"
#           git config user.email "actions@github.com"

#           git add -A
          
#           git commit -m "Розпаковано GoatZefalator.zip та додано .pck в LFS" || echo "Немає змін"
          
#           git push
